- name: Install OS dependencies via apt
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - apache2

- name: Enable apache modules
  apache2_module:
    state: present
    name: '{{item}}'
  with_items: '{{apache2_modules}}'

- name: Add switch apt key
  apt_key:
    url: http://pkg.switch.ch/switchaai/SWITCHaai-swdistrib.asc
    state: present
    id: 294E37D154156E00FB96D7AA26C3C46915B76742

- name: Add switch apt repo
  apt_repository:
    repo: deb http://pkg.switch.ch/switchaai/debian stretch main
    state: present

- name: Install shibboleth
  apt:
    name: shibboleth

