- name: Install OS dependencies via apt
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - apache2

- name: Enable apache modules
  apache2_module:
    state: present
    name: '{{item}}'
  with_items: '{{apache2_modules}}'

- name: Add phusionpassenger apt key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 561F9B9CAC40B2F7
    state: present

- name: Add phusionpassenger apt repo
  apt_repository:
    repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger stretch main
    state: present

- name: Install libapache2-mod-passenger
  apt:
    name: libapache2-mod-passenger

- name: Enable libapache2-mod-passenger
  apache2_module:
    name: passenger
    state: present

- name: Check phusionpassenger installation
  shell: /usr/bin/passenger-config validate-install --auto
