- file:
    path: /etc/apache2/{{app_name}}/
    state: directory
    mode: 0755

- name: copy apache shared config file
  template:
    src: shared.conf
    dest: /etc/apache2/{{app_name}}/shared.conf
    mode: 0644

- name: copy apache http config file
  template:
    src: apache.conf
    dest: /etc/apache2/{{app_name}}/apache.conf
    mode: 0644

- name: enable http site/config
  file:
    state: link
    src: /etc/apache2/{{app_name}}/apache.conf
    dest: /etc/apache2/sites-enabled/{{app_name}}.conf

- name: copy apache https config file
  template:
    src: apache_ssl.conf
    dest: /etc/apache2/{{app_name}}/apache_ssl.conf
    mode: 0644

- name: enable https site/config
  file:
    state: link
    src: /etc/apache2/{{app_name}}/apache_ssl.conf
    dest: /etc/apache2/sites-enabled/{{app_name}}_ssl.conf

- name: restart apache
  service:
    name: apache2
    state: restarted

